# -*- coding: utf-8 -*-
"""ImageColorSpace.ipynb

Automatically generated by Colaboratory.
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow


def displayImage(image, title):
  print("\n")
  print(title)
  cv2_imshow(image)


def showImageWithAllColorSpaces(image):
  for colorSpace in colorSpaces:
    img = getColorSpace(image, colorSpace)
    img = img.astype(np.float64)
    displayImage(img, "Imagen " + colorSpace)

    R = img[:,:,0]
    G = img[:,:,1]
    B = img[:,:,2]

    colorComp = cv2.hconcat((R,G,B))
    cv2_imshow(colorComp)


def getColorSpace(image, cs):
  img = np.copy(image)
  if cs is None or "rgb" == cs.lower():
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  elif "hsv" == cs.lower():
    return cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
  elif "lab" == cs.lower():
    return cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
  return img


image = cv2.imread('/content/drive/MyDrive/vision_artificial/images/galletas.jpg', cv2.IMREAD_COLOR)
displayImage(image, "Imagen original")
colorSpaces = ["RGB", "HSV", "LAB"]
showImageWithAllColorSpaces(image)