# -*- coding: utf-8 -*-
"""ImageColorSpace.ipynb

Automatically generated by Colaboratory.
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt


def displayImage(img, title):
    print("\n")
    print(title)
    cv2.imshow(title, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


def showImageWithAllColorSpaces(img_in):
    for colorSpace in colorSpaces:
        img = img_in.copy()
        img = getColorSpace(img, colorSpace)
        displayImage(img, "Imagen " + colorSpace)
        img = img.astype(np.float64)

        R = img[:, :, 0]
        G = img[:, :, 1]
        B = img[:, :, 2]

        colorComp = cv2.hconcat((R, G, B))
        plt.imshow(colorComp, cmap="gray")
        plt.show()


def getColorSpace(img, cs):
    img = np.copy(img)
    if cs is None or "rgb" == cs.lower():
        return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    elif "hsv" == cs.lower():
        return cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    elif "lab" == cs.lower():
        return cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    return img


image = cv2.imread('../data/galletas.jpg', cv2.IMREAD_COLOR)
displayImage(image, "Imagen original")
colorSpaces = ["RGB", "HSV", "LAB"]
showImageWithAllColorSpaces(image)
